name: pet_care_tracker
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  bloc: ^8.1.4
  get_it: ^8.0.2
  shimmer: ^3.0.0
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  curved_navigation_bar: ^1.0.1
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  mockito: ^5.4.4

flutter:

  uses-material-design: true

