// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT5McFcJ8-vO_iu0GSnytdNwM5LpFnCrM',
    appId: '1:882067190442:web:b1ffd2cb1f4e4923ec96d3',
    messagingSenderId: '882067190442',
    projectId: 'pet-tracker-22c69',
    authDomain: 'pet-tracker-22c69.firebaseapp.com',
    storageBucket: 'pet-tracker-22c69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEGNIID6nXnBJoNSZvfZlMesxBw-vD8n4',
    appId: '1:882067190442:android:27e4cef74d9f5ffcec96d3',
    messagingSenderId: '882067190442',
    projectId: 'pet-tracker-22c69',
    storageBucket: 'pet-tracker-22c69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEu528dxwjf7CwN21qbxde0nwiJM_7rQo',
    appId: '1:882067190442:ios:29a8725e2b89c377ec96d3',
    messagingSenderId: '882067190442',
    projectId: 'pet-tracker-22c69',
    storageBucket: 'pet-tracker-22c69.firebasestorage.app',
    iosBundleId: 'com.example.petCareTracker',
  );
}
